### PR TITLE
(#115) Support additional broker configuration

### LINKED ISSUE #115: Add support for additional config keys
Support adding additional keys by way of data in hiera

### PR DESCRIPTION
**Pull request by vjanelle**
Fixes #115

Support adding additional keys by way of data in hiera - things like
specifying file security, etc.

### CODE REVIEW

**Comment by vjanelle** [comment]
Can add tests if you're ok with this approach.  Or I can just make it work the same way as the other ones do, but you'd lose the comments.

**Comment by ripienaar** [comment]
Tests would be good yeah - not many of my modules have tests, this one does so might as well keep it current

Also fix commit format please, I think this is a good approach

**Comment by vjanelle** [comment]
Commit format?

**Comment by ripienaar** [comment]
like `(#115) blah blah` as first line and squash all

**Comment by vjanelle** [comment]
Oops.  Right.

**Comment by ripienaar** [comment]
closed in favor of https://github.com/choria-io/puppet-choria/pull/149

**Pull request closed without merging**
