### PR TITLE
(#331) Adds the architecture parameter to remove warnings about unsupported architectures

### LINKED ISSUE #331: Support the architecture for Debian repositories
Debian repositories on multi-arch systems issue the following warning if the package source doesn't support all architectures:

```
N: Skipping acquire of configured file 'jammy/binary-i386/Packages' as repository 'mirror://mirrorlists.choria.io/apt/release/ubuntu/jammy/mirrors.txt ubuntu InRelease' doesn't support architecture 'i386'
```

To circumvent that, the choria repo should include the "archicture" parameter set to the system architecture.

I'll add a PR to issue that.

### PR DESCRIPTION
**Pull request by dploeger**
…ported architectures

closes #331

### CODE REVIEW

**Comment by ripienaar** [comment]
Whats the error or warning this causes?

**Comment by dploeger** [comment]
The warning is

``` 
N: Skipping acquire of configured file 'jammy/binary-i386/Packages' as repository 'mirror://mirrorlists.choria.io/apt/release/ubuntu/jammy/mirrors.txt ubuntu InRelease' doesn't support architecture 'i386'
```

**Comment by ripienaar** [comment]
Thanks, are you able to sign your commits @dploeger ?

**Comment by dploeger** [comment]
@ripienaar Done.

**Pull request merged**
