### PR TITLE
Add repo gpg checking option

### PR DESCRIPTION
**Pull request by legooolas**
GPG keys are specified but not used at all at present.

It seems that packagecloud sets up repo GPG signing, but not package signing, so I've just enabled that for now.  Is it also possible to enable package signing, or does the repo signing make this unnecessary?

### CODE REVIEW

**Comment by ripienaar** [comment]
There's good reason for this unfortunately https://github.com/choria-io/puppet-choria/pull/112

**Comment by legooolas** [comment]
How about this with an option for enabling it?  :)

**Comment by ripienaar** [comment]
Yeah but we'd probably need to default to false while we give people headsups or something? Some people will now rely on this behaviour

**Comment by legooolas** [comment]
Fine by me  :)

**Comment by ripienaar** [comment]
ok, please follow CONTRIBUTING.md for commit style, issue etc.  thanks

**Pull request closed without merging**
