### PR TITLE
(#355) Switched to the static key URL to optimize key downloads 

### PR DESCRIPTION
**Pull request by dploeger**
Changing the GPG key link as provided in https://github.com/choria-io/general/discussions/47#discussioncomment-8955361

### CODE REVIEW

**Comment by dploeger** [comment]
I don't believe the checks failed because of my change...

**Comment by ripienaar** [comment]
Please reference https://github.com/choria-io/puppet-choria/issues/355 in the commit, examples in history and the contributors guide

**Comment by dploeger** [comment]
Done

**Comment by ripienaar** [comment]
Thank you!

**Comment by ripienaar** [comment]
I hope to do so soon, just returned from a few weeks off and have 4 months of travel coming, will try squeeze it before next travel

**Comment by dploeger** [comment]
@ripienaar Do you think you can find some time to release this?

**Comment by ripienaar** [comment]
Yes, there's another bug fix nats release due will do after.

**Comment by dploeger** [comment]
Great! Thanks.

**Pull request merged**
