### PR TITLE
(#195) Support yum repos on CentOS 8

### PR DESCRIPTION
**Pull request by bastelfreak**
@ripienaar @vchepkov I didn't test this. If I get the logic right, this will use `$releasever` on centos 7 and 8.

### CODE REVIEW

**Comment by vchepkov** [comment]
This will break Fedora

**Comment by bastelfreak** [comment]
but does choria even support fedora? It's not listed in the metadata.json. If so, which repo URL should we configure on Fedora?

**Comment by ripienaar** [comment]
I don't care for Fedora and dont intend to test anything on it

**Comment by vchepkov** [comment]
breaks rhel6 too

**Comment by ripienaar** [comment]
rhel6 support can go away

**Pull request merged**
