### PR TITLE
(#36) add description to yum repositories

### PR DESCRIPTION
**Pull request by vchepkov**
prior to this commit repo files were missing mandatory 'name' option

### CODE REVIEW

**Comment by ripienaar** [comment]
Hmm not sure this is mandatory I use this class a lot as is?

What was the error?

Please for PRs create issues and use the commit message format that match other commits

**Comment by vchepkov** [comment]
It doesn't fail, but emits warning with each yum run:

```
# yum check-update
Loaded plugins: fastestmirror
Repository 'choria_release' is missing name in configuration, using id
```

**Comment by ripienaar** [comment]
ah ok - if you dont mind please:

 * make a issue in this repo
 * fix spelling of `builts` should be `builds`
 * rebase the pr to master
 * change commit to `(#nn) add description to yum repositories` where nn is the ticket you made

**Comment by vchepkov** [comment]
Done

**Pull request merged**
